# Generated by Django 5.2.14 on 2026-05-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='callback_data',
            field=models.JSONField(blank=True, help_text='Données brutes reçues du webhook opérateur', null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='code_ussd',
            field=models.CharField(blank=True, help_text='Code USSD à composer', max_length=100),
        ),
        migrations.AddField(
            model_name='paiement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='message_operateur',
            field=models.CharField(blank=True, help_text="Message retourné par l'opérateur", max_length=500),
        ),
        migrations.AddField(
            model_name='paiement',
            name='tentatives',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="Identifiant de transaction chez l'opérateur", max_length=200),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('flooz', 'Flooz (Moov Africa)'), ('tmoney', 'T-Money (Togocom)'), ('carte', 'Carte Bancaire'), ('especes', 'Espèces à la livraison')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('initie', 'Initié'), ('en_cours', 'En cours de traitement'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20),
        ),
    ]
