services:
  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-centremagnim}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-KARa@40bou}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kabiye-net
    restart: always

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-centremagnim.com,www.centremagnim.com,localhost,127.0.0.1}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-https://centremagnim.com,https://www.centremagnim.com}
      - DB_NAME=${DB_NAME:-centremagnim}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-KARa@40bou}
      - DB_HOST=${DB_HOST:-postgres-db}
      - DB_PORT=${DB_PORT:-5432}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      # Brevo configurations for emails
      - BREVO_SMTP_HOST=${BREVO_SMTP_HOST:-smtp-relay.brevo.com}
      - BREVO_SMTP_PORT=${BREVO_SMTP_PORT:-587}
      - BREVO_SMTP_TLS=${BREVO_SMTP_TLS:-True}
      - BREVO_SMTP_SSL=${BREVO_SMTP_SSL:-False}
      - BREVO_SMTP_LOGIN=${BREVO_SMTP_LOGIN}
      - BREVO_SMTP_KEY=${BREVO_SMTP_KEY}
    networks:
      - kabiye-net
      - dokploy-network
    depends_on:
      - postgres-db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"
      - "traefik.http.routers.kabiye-books.rule=Host(`centremagnim.com`) || Host(`www.centremagnim.com`)"
      - "traefik.http.routers.kabiye-books.entrypoints=web"
      - "traefik.http.services.kabiye-books.loadbalancer.server.port=8000"

volumes:
  postgres_data:

networks:
  kabiye-net:
    driver: bridge
  dokploy-network:
    external: true