kind = "web"
previewPath = "/"
title = "KabiyèBooks"
version = "1.0.0"

[[services]]
localPort = 8000
name = "KabiyèBooks Django"
paths = ["/"]

[services.development]
run = "cd kabiye-books && gunicorn kabiye_books.wsgi:application --bind 0.0.0.0:8000 --workers 2"
