# Generated by Django 5.2.14 on 2026-05-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='couleur',
            field=models.CharField(default='#2d8a47', help_text='Couleur hex ex: #2d8a47', max_length=20),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='gestion_categories.categorie', verbose_name='Catégorie parente'),
        ),
    ]
