# Generated by Django 5.2.14 on 2026-05-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_categories', '0001_initial'),
        ('gestion_livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avislivre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favori',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='gestion_categories.categorie'),
        ),
        migrations.AddField(
            model_name='livre',
            name='langue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_livres.langue'),
        ),
        migrations.AddField(
            model_name='imagelivre',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion_livres.livre'),
        ),
        migrations.AddField(
            model_name='favori',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='gestion_livres.livre'),
        ),
        migrations.AddField(
            model_name='avislivre',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='gestion_livres.livre'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('utilisateur', 'livre')},
        ),
        migrations.AlterUniqueTogether(
            name='avislivre',
            unique_together={('livre', 'auteur')},
        ),
    ]
