# Generated by Django 5.2.14 on 2026-05-25 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_commandes', '0002_initial'),
        ('gestion_livres', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='livres/pdf/'),
        ),
        migrations.AddField(
            model_name='livre',
            name='prix_pdf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le même prix que le livre physique', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='type_vente',
            field=models.CharField(choices=[('physique', 'Livre physique uniquement'), ('numerique', 'Livre numérique (PDF) uniquement'), ('les_deux', 'Physique + PDF')], default='physique', max_length=20),
        ),
        migrations.CreateModel(
            name='TelechargementPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nombre_telechargements', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telechargements', to='gestion_commandes.commande')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to='gestion_livres.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telechargements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Téléchargement PDF',
                'ordering': ['-date'],
                'unique_together': {('utilisateur', 'livre')},
            },
        ),
    ]
