# Generated by Django 6.0.5 on 2026-06-04 15:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_livres', '0003_add_pdf_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='livres/pdf/'),
        ),
    ]
