# Generated by Django 5.2.14 on 2026-05-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_livraison', models.CharField(choices=[('domicile', 'Livraison à domicile'), ('nationale', 'Livraison nationale'), ('internationale', 'Livraison internationale')], default='domicile', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('numero_suivi', models.CharField(blank=True, max_length=100)),
                ('transporteur', models.CharField(blank=True, max_length=100)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='gestion_commandes.commande')),
            ],
            options={
                'verbose_name': 'Livraison',
            },
        ),
    ]
