# Generated by Django 5.2.14 on 2026-05-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('prepare', 'En préparation'), ('expedie', 'Expédié'), ('en_transit', 'En transit'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Échec de livraison')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='transporteur',
            field=models.CharField(blank=True, default='KabiyèBooks Express', max_length=100),
        ),
        migrations.CreateModel(
            name='LivraisonEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prepare', 'En préparation'), ('expedie', 'Expédié'), ('en_transit', 'En transit'), ('en_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec', 'Échec de livraison')], max_length=20)),
                ('lieu', models.CharField(blank=True, default='Lomé, Togo', max_length=200)),
                ('description', models.TextField()),
                ('icone', models.CharField(default='bi-circle-fill', max_length=50)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='gestion_livraisons.livraison')),
            ],
            options={
                'verbose_name': 'Événement de livraison',
                'verbose_name_plural': 'Événements de livraison',
                'ordering': ['-date'],
            },
        ),
    ]
